<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<!-- Target Piattaforma: Android -->
		<TargetFrameworks>net10.0-android</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>TimingCalc</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnableDefaultCssItems>false</EnableDefaultCssItems>
		<Nullable>enable</Nullable>

		<MauiXamlInflator>SourceGen</MauiXamlInflator>

		<!-- Display name -->
		<ApplicationTitle>TimingCalc</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.timingcalc</ApplicationId>

		<!-- Versions -->
		<Version>1.0.1</Version>
		<PackageVersion>1.0.1</PackageVersion>
		<ApplicationDisplayVersion>1.0.1</ApplicationDisplayVersion>
		<ApplicationVersion>2</ApplicationVersion>

		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<!-- Configurazione Firma APK Release per Android (Universale) -->
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' AND '$(Configuration)' == 'Release'">
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<AndroidKeyStore>True</AndroidKeyStore>
		<AndroidSigningKeyStore>secrets/timingcalc.keystore</AndroidSigningKeyStore>
		<AndroidSigningStorePass>!xsdrAE4ZVFyH5w27skDD</AndroidSigningStorePass>
		<AndroidSigningKeyAlias>timingcalc</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>!xsdrAE4ZVFyH5w27skDD</AndroidSigningKeyPass>
	</PropertyGroup>

	<!-- Configurazione Debug per Android -->
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' AND '$(Configuration)' == 'Debug'">
		<AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<!-- Protezione AOT in Release -->
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<RunAOTCompilation>true</RunAOTCompilation>
	</PropertyGroup>

	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.png" ForegroundFile="Resources\AppIcon\appicon.png" Color="#FFFFFF" />
		<MauiImage Include="Resources\Images\*" />
		<MauiFont Include="Resources\Fonts\*" />
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="14.1.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.41" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Secrets\" />
	</ItemGroup>

</Project>